In [1]:
import numpy as np

In [2]:
my_matrix = np.array([[0, 0, 0], [1, 1, 0], [1, 0, 1]])  #Initial matrix
second_matrix = np.array([[1, 0, 0], [1, 1, 0], [0, 1, 0]])
third_matrix = np.array([[1, 0, 1], [1, 0, 0], [0, 1, 0]])
final_matrix = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])  #Final matrix which needs to obtain as a result
print("First matrix:\n", my_matrix)
print("Second matrix:\n", second_matrix)
print("Third matrix:\n", third_matrix)
print("Goal:\n", final_matrix)

First matrix:
 [[0 0 0]
 [1 1 0]
 [1 0 1]]
Second matrix:
 [[1 0 0]
 [1 1 0]
 [0 1 0]]
Third matrix:
 [[1 0 1]
 [1 0 0]
 [0 1 0]]
Goal:
 [[0 0 0]
 [0 1 0]
 [0 0 0]]


In [3]:
#Function for matrix omparison
def compare(arr1, arr2):
    
    x = arr1 == arr2
    return x.all()

#Function to toggle the values
def toggle(value):
    
    if(value == 1):
        value = 0
    else:
        value = 1
        
    return value

In [4]:
def magic_square(arr, row, col):
    
    k = row
    l = col
 
    if(k == 0 and l == 0):
        arr[k][l] = toggle(arr[k][l])
        arr[k+1][l] = toggle(arr[k+1][l])
        arr[k][l+1] = toggle(arr[k][l+1])
        arr[k+1][l+1] = toggle(arr[k+1][l+1])

    elif(k == 0 and l == 2):
        arr[k][l] = toggle(arr[k][l])
        arr[k][l-1] = toggle(arr[k][l-1])
        arr[k+1][l] = toggle(arr[k+1][l])
        arr[k+1][l-1] = toggle(arr[k+1][l-1])

    elif(k == 2 and l == 0):
        arr[k][l] = toggle(arr[k][l])
        arr[k-1][l] = toggle(arr[k-1][l])
        arr[k][l+1] = toggle(arr[k][l+1])
        arr[k-1][l+1] = toggle(arr[k-1][l+1])

    elif(k == 2 and l == 2):
        arr[k][l] = toggle(arr[k][l])
        arr[k][l-1] = toggle(arr[k][l-1])
        arr[k-1][l] = toggle(arr[k-1][l])
        arr[k-1][l-1] = toggle(arr[k-1][l-1])

    elif((k == 0 and l==1) or (k == 2 and l==1)):
        arr[k][l] = toggle(arr[k][l])
        arr[k][l+1] = toggle(arr[k][l+1])
        arr[k][l-1] = toggle(arr[k][l-1])

    elif((k == 1 and l==0) or (k == 1 and l==2)):
        arr[k][l] = toggle(arr[k][l])
        arr[k+1][l] = toggle(arr[k+1][l])
        arr[k-1][l] = toggle(arr[k-1][l])

    elif(k == 1 and l==1):
        arr[k][l] = toggle(arr[k][l])
        arr[k][l+1] = toggle(arr[k][l+1])
        arr[k][l-1] = toggle(arr[k][l-1])
        arr[k+1][l] = toggle(arr[k+1][l])
        arr[k-1][l] = toggle(arr[k-1][l])
        
    else:
        print("Enter the correct values or rows and columns")
                
    return arr

N = 3
M = 3

In [5]:
def game_run(input_matrix, result_matrix):
    
    n = 0
    mat = input_matrix
    result_mat = result_matrix
    result = compare(mat, result_mat)
    while result==False:
        print(mat)
        print("Choose the box of matrix by providing values of row and column.")
        row, col = input("Enter the value of row and then column (0-2):").split()
        row = int(row)
        col = int(col)
        print("The selected values for row and column:", row, col)
        mat = magic_square(mat, row, col)
        n +=1
        result = compare(mat, result_mat)

        if(n > 1000):
            print("The number of iterations exceeds.")
            print("Final matrix:", mat)
            break

    print("The matrix is equal to the final matrix:", mat)
    print("Number of iteration: ", n)

In [6]:
select = input("Choose the matrix to play with(enter 1,2 or 3):\n")
select = int(select)

if(select == 1):
    selected_matrix = my_matrix
    print("Matrix 1 has been selected:\n", selected_matrix)
elif(select == 2):
    selected_matrix = second_matrix
    print("Matrix 2 has been selected:\n", selected_matrix)
elif(select == 3):
    selected_matrix = third_matrix
    print("Matrix 3 has been selected:\n", selected_matrix)
else:
    print("Invalid selection!")
    print("Program terminating!")

Choose the matrix to play with(enter 1,2 or 3):
 2


Matrix 2 has been selected:
 [[1 0 0]
 [1 1 0]
 [0 1 0]]


In [7]:
#Running a program

if selected_matrix.all():
    print("No matrix has been selected")
else:
    print("Matrix has been selected")
    game_run(selected_matrix, final_matrix)

Matrix has been selected
[[1 0 0]
 [1 1 0]
 [0 1 0]]
Choose the box of matrix by providing values of row and column.


Enter the value of row and then column (0-2): 2 2


The selected values for row and column: 2 2
[[1 0 0]
 [1 0 1]
 [0 0 1]]
Choose the box of matrix by providing values of row and column.


Enter the value of row and then column (0-2): 1 2


The selected values for row and column: 1 2
[[1 0 1]
 [1 0 0]
 [0 0 0]]
Choose the box of matrix by providing values of row and column.


Enter the value of row and then column (0-2): 1 0


The selected values for row and column: 1 0
[[0 0 1]
 [0 0 0]
 [1 0 0]]
Choose the box of matrix by providing values of row and column.


Enter the value of row and then column (0-2): 0 2


The selected values for row and column: 0 2
[[0 1 0]
 [0 1 1]
 [1 0 0]]
Choose the box of matrix by providing values of row and column.


Enter the value of row and then column (0-2): 2 0


The selected values for row and column: 2 0
[[0 1 0]
 [1 0 1]
 [0 1 0]]
Choose the box of matrix by providing values of row and column.


Enter the value of row and then column (0-2): 1 1


The selected values for row and column: 1 1
The matrix is equal to the final matrix: [[0 0 0]
 [0 1 0]
 [0 0 0]]
Number of iteration:  6
